name: Test CI
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOs-latest]

    env:
      DENO_VERSION: 1.0.3
      RUST_VERSION: 1.43.1
      GH_ACTIONS: true
      RUST_BACKTRACE: full
      DENO_BUILD_MODE: release

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add msvc to PATH
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ env.RUST_VERSION }}

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Log versions
        run: |
          node -v
          deno --version
          rustc --version
          cargo --version

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Remove Some Cache
        if: matrix.os == 'windows-latest'
        run: |
          rm target/release/gn_root -Recurse -ErrorAction Ignore
          rm target/debug/gn_root -Recurse -ErrorAction Ignore

      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: "2.7.x"
          architecture: x64

      - name: Install mpv [linux]
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install mpv libmpv-dev

      - name: Install mpv [mac]
        if: matrix.os == 'macOS-latest'
        run: |
          brew install mpv

      - name: Import libmpv
        run: deno run --unstable -A ./scripts/libmpv.ts

      - name: Build
        env:
          RUST_BACKTRACE: 1
        run: cargo build -vv --release --features build_libmpv

      - name: Fix dylib [mac]
        if: matrix.os == 'macOS-latest'
        run: |
          ./scripts/fix_dylib.sh

      - name: Release Plugin
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "deno_mpv release"
          draft: true
          files: |
            target/release/libdeno_mpv.dylib
            target/release/libdeno_mpv.so
            target/release/deno_mpv.dll
